<?php

return [
    'essential' => [
        'name' => 'Essential',
        'price_lkr' => 35000,
        'price_display' => 'LKR 350/month',
        'payhere_recurrence' => '1 Month',
        'tagline' => 'Perfect for startups & small stores',
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
        ],
    ],
    'growth' => [
        'name' => 'Growth Plan (Most Popular)',
        'description' => 'Best for growing retail shops.',
        'max_branches' => 3,
        'max_users' => 5,
        'price_lkr' => 35000,
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
            'loyalty_customers',
            'profit_loss_report',
            'expiry_tracking',
            'item_wise_sales_report',
            'category_wise_sales_report',
            'other_expenses_tracking',
            'batch_tracking_fifo',
            'receipt_customization',
            'supplier_management',
        ],
    ],
    'professional' => [
        'name' => 'Professional',
        'price_lkr' => 85000,
        'price_display' => 'LKR 850/month',
        'payhere_recurrence' => '1 Month',
        'tagline' => 'For growing businesses',
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
            'loyalty_customers',
            'profit_loss_report',
            'expiry_tracking',
            'item_wise_sales_report',
            'category_wise_sales_report',
            'other_expenses_tracking',
            'batch_tracking_fifo',
            'receipt_customization',
            'supplier_management',
            'advanced_inventory_controls',
            'multi_branch_reporting',
            'centralized_dashboard',
            'staff_permission_roles',
            'priority_support',
            'sales_inventory_forecasting',
        ],
    ],
    'enterprise' => [
        'name' => 'Enterprise',
        'price_lkr' => 175000,
        'price_display' => 'LKR 1,750/month',
        'payhere_recurrence' => '1 Month',
        'tagline' => 'For retail chains & large stores',
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
            'loyalty_customers',
            'profit_loss_report',
            'expiry_tracking',
            'item_wise_sales_report',
            'category_wise_sales_report',
            'other_expenses_tracking',
            'batch_tracking_fifo',
            'receipt_customization',
            'supplier_management',
            'advanced_inventory_controls',
            'multi_branch_reporting',
            'centralized_dashboard',
            'staff_permission_roles',
            'priority_support',
            'sales_inventory_forecasting',
            'custom_api_integration',
            'white_label_branding',
            'dedicated_account_manager',
            'on_site_training',
            'custom_feature_development',
        ],
    ],
];