<?php

return [
    'starter' => [
        'name' => 'Starter Plan (Small Shops)',
        'description' => 'Good for small grocery shops or kiosks.',
        'max_branches' => 1,
        'max_users' => 2,
        'price_lkr' => 15000,
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
        ],
    ],
    'growth' => [
        'name' => 'Growth Plan (Most Popular)',
        'description' => 'Best for growing retail shops.',
        'max_branches' => 3,
        'max_users' => 5,
        'price_lkr' => 35000,
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
            'loyalty_customers',
            'profit_loss_report',
            'expiry_tracking',
            'item_wise_sales_report',
            'category_wise_sales_report',
            'other_expenses_tracking',
            'batch_tracking_fifo',
            'receipt_customization',
            'supplier_management',
        ],
    ],
    'business' => [
        'name' => 'Business Plan (Large Stores)',
        'description' => 'For supermarkets, chains, or serious retailers.',
        'max_branches' => -1, // Unlimited
        'max_users' => -1, // Unlimited
        'price_lkr' => 75000,
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
            'loyalty_customers',
            'profit_loss_report',
            'expiry_tracking',
            'item_wise_sales_report',
            'category_wise_sales_report',
            'other_expenses_tracking',
            'batch_tracking_fifo',
            'receipt_customization',
            'supplier_management',
            'advanced_inventory_controls',
            'multi_branch_reporting',
            'centralized_dashboard',
            'staff_permission_roles',
            'priority_support',
            'sales_inventory_forecasting',
        ],
    ],
    'custom' => [
        'name' => 'Custom Plan (Enterprise)',
        'description' => 'For supermarkets, chains, or serious retailers with unique needs.',
        'max_branches' => -1, // Unlimited
        'max_users' => -1, // Unlimited
        'price_lkr' => 0, // Handled in UI
        'features' => [
            'product_management',
            'barcode_support',
            'pos_billing',
            'basic_inventory_tracking',
            'grn',
            'cash_summary',
            'sales_reports_daily_weekly',
            'inventory_value_report',
            'loyalty_customers',
            'profit_loss_report',
            'expiry_tracking',
            'item_wise_sales_report',
            'category_wise_sales_report',
            'other_expenses_tracking',
            'batch_tracking_fifo',
            'receipt_customization',
            'supplier_management',
            'advanced_inventory_controls',
            'multi_branch_reporting',
            'centralized_dashboard',
            'staff_permission_roles',
            'priority_support',
            'sales_inventory_forecasting',
            'custom_api_integration',
            'white_label_branding',
            'dedicated_account_manager',
            'on_site_training',
            'custom_feature_development',
        ],
    ],
];
